build:
  environment:
    php: 
      version: "8.1"
      pecl_extensions:
        - xdebug
  tests:
    override:
      - command: "vendor/bin/phpunit --coverage-clover=clover.xml --exclude-group flaky"
        coverage:
          file: "logs/clover.xml"
          format: "clover"
      - php-scrutinizer-run
