language: php

matrix:
  include:
    - php: 8.1
      env:
        - psalm=yes
      dist: jammy
    #ppc64le support code
    - php: 8.1
      arch: ppc64le
      env:
        - psalm=yes
      dist: jammy

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; else composer install; fi
  - if [ "$psalm" = "yes" ]; then composer require --dev vimeo/psalm; fi

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --exclude-group flaky
  - if [ "$psalm" = "yes" ]; then vendor/bin/psalm; fi

after_script:
  - php vendor/bin/coveralls
