name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      CC_TEST_REPORTER_ID: 4e98538db53370a2c9c8187d297a014a9520d0c26424f926f8678fe043a771fe

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1', '8.2']
        deps: [highest]

        include:
          - php: '8.1'
            deps: lowest

    name: PHP ${{ matrix.php }} / ${{ matrix.deps }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.deps }}

      - name: Setup logs directory
        run: mkdir -p build/logs

      - name: code climate reporter
        run: | 
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter

      - name: Execute tests
        run: | 
        vendor/bin/phpunit --coverage-clover clover.xml --exclude-group flaky 
        ./cc-test-reporter after-build -t clover --exit-code $?

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: ./
      
